// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOipX0Zr1ElMGcHfM1uW4ddkNLISl2gQ0',
    appId: '1:772929384764:web:3e95ef2c53d2aedef76e39',
    messagingSenderId: '772929384764',
    projectId: 'word-bucket-90aa0',
    authDomain: 'word-bucket-90aa0.firebaseapp.com',
    databaseURL: 'https://word-bucket-90aa0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'word-bucket-90aa0.appspot.com',
    measurementId: 'G-6RH3QB4SWH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJXzRoSePgujhgYnYYyoLq4lcJo7D2pyk',
    appId: '1:772929384764:android:d1da5ec168915c18f76e39',
    messagingSenderId: '772929384764',
    projectId: 'word-bucket-90aa0',
    databaseURL: 'https://word-bucket-90aa0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'word-bucket-90aa0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_jZN1bSm7advVQoB9XsZthSNgE77D-yU',
    appId: '1:772929384764:ios:121790820b2f131ef76e39',
    messagingSenderId: '772929384764',
    projectId: 'word-bucket-90aa0',
    databaseURL: 'https://word-bucket-90aa0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'word-bucket-90aa0.appspot.com',
    iosClientId: '772929384764-r436r099u8vbivbra5agqbo6jflu85k4.apps.googleusercontent.com',
    iosBundleId: 'com.dreamsparser.wordbucket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_jZN1bSm7advVQoB9XsZthSNgE77D-yU',
    appId: '1:772929384764:ios:8698008c481a1b7df76e39',
    messagingSenderId: '772929384764',
    projectId: 'word-bucket-90aa0',
    databaseURL: 'https://word-bucket-90aa0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'word-bucket-90aa0.appspot.com',
    iosClientId: '772929384764-dhca5pp3mecln3cfm2n1i1mten0ca7sk.apps.googleusercontent.com',
    iosBundleId: 'com.dreamsparser.app',
  );
}
